id: P000286
initial_creation_type: ocr
created_at: 21/02/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W27487
  title: མན་ངག་གནད་ཀྱི་རྫོང་འཕྲང་གི་སྐོར།
  author: ''
  volumes:
    ea4d44fcf0dd4bd8823f38e9861b677e:
      image_group_id: I4500
      title: ''
      volume_number: 1
      total_pages: 614
      base_file: v001.txt
